/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as IndexRouteImport } from './routes/index'

const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/philosophy': typeof PhilosophyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/philosophy': typeof PhilosophyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/philosophy': typeof PhilosophyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advisory' | '/contact' | '/journal' | '/philosophy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advisory' | '/contact' | '/journal' | '/philosophy'
  id: '__root__' | '/' | '/advisory' | '/contact' | '/journal' | '/philosophy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  PhilosophyRoute: typeof PhilosophyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  PhilosophyRoute: PhilosophyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
